### ISSUE TITLE
Questions about multi-GPU training

### ISSUE THREAD

**Issue by xhh232018** [JiahuiYu/generative_inpainting#63]
Hi, Jiahui. I see your comments on #14 but it cannot solve my problem. Same situation happens again. When I changed the the line you mentioned in #14  into "MultiGPUTrainer". The error is
 Traceback (most recent call last):
  File "train.py", line 100, in <module>
    log_dir=log_prefix,
  File "/home/mc/miniconda3/envs/DRL/lib/python3.6/site-packages/neuralgym/train/multigpu_trainer.py", line 27, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "/home/mc/miniconda3/envs/DRL/lib/python3.6/site-packages/neuralgym/train/multigpu_trainer.py", line 70, in train_ops_and_losses
    assert loss is None('For multigpu training, graph_def and kwargs'
TypeError: 'NoneType' object is not callable, which is the same as other users in #14 .
I thought the reason why this kind of error came out is the line 70 of multigpu_trainer.py so that I commented out this line. However, a new error showed :  Traceback (most recent call last):
  File "train.py", line 101, in <module>
    num_gpus=2
  File "/home/mc/miniconda3/envs/DRL/lib/python3.6/site-packages/neuralgym/train/multigpu_trainer.py", line 27, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "/home/mc/miniconda3/envs/DRL/lib/python3.6/site-packages/neuralgym/train/multigpu_trainer.py", line 99, in train_ops_and_losses
    grads = average_gradients(tower_grads)
  File "/home/mc/miniconda3/envs/DRL/lib/python3.6/site-packages/neuralgym/ops/train_ops.py", line 22, in average_gradients
    grad = tf.add_n([x[0] for x in grad_and_vars])
NameError: name 'tf' is not defined

Therefore, I need your help.  Thanks a lot!

**Comment by JiahuiYu** [comment]
I've fixed bug. Please try to reinstall neuralgym with 
`pip install git+https://github.com/JiahuiYu/neuralgym --upgrade`

**Comment by unlugi** [comment]
Hello, thank you for sharing your work.
But I am still unable to work with multiple gpu's , I have tried to follow the steps in issue #14 , and also upgraded the neuralgym library 
![resim](https://user-images.githubusercontent.com/15035152/42062811-91b09856-7b37-11e8-8099-5e9c2d03195d.png)

**Comment by unlugi** [comment]
I have also modified the inpaint.yml file (NUM_GPUS  &  GPU_ID)

**Comment by JiahuiYu** [comment]
@unlugi Please add `num_gpus=config.NUM_GPUS` arguments when you claim MultiGPUTrainer.

**Comment by Adhiyaman-Manickam** [comment]
@unlugi. Hi. Have you figured out an issues that how to use multi gpu for training. If so, kindly let me know.
